name: Sunnysport_Action

on:
  push:
    branches: main
  watch:
    types: started
  schedule:
    - cron: '0 12 * * *'

env:
  UID: ${{ secrets.UID }}
  SENDKEY: ${{ secrets.SENDKEY }}
  MINSPEED: ${{ secrets.MINSPEED }}
  MINMILEAGE: ${{ secrets.MINMILEAGE }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: run program
      run: |
        python main.py
